name: Professional Cloud Sync
on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Source Link (Discord/Drive)'
        required: true
      file_name:
        description: 'New Name (e.g., Premiere_2020.zip)'
        required: true

jobs:
  transfer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetching Asset
        run: curl -L "${{ github.event.inputs.file_url }}" -o "${{ github.event.inputs.file_name }}"

      - name: Create Professional Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0-assets"
          files: "${{ github.event.inputs.file_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
